# Generated by Django 4.1.4 on 2023-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponser_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_link', models.CharField(max_length=300)),
                ('product_images', models.ImageField(upload_to='\\static\\images')),
            ],
        ),
    ]
