# Generated by Django 4.1.4 on 2023-02-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sponser_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser_products',
            name='product_images',
            field=models.ImageField(upload_to='pricecomparision/static/images'),
        ),
        migrations.AlterField(
            model_name='sponser_products',
            name='product_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sponser_products',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
