# Generated by Django 4.1.4 on 2023-03-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_sponser_products_product_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sponser_products',
        ),
    ]
