# Generated by Django 4.1.4 on 2023-03-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_sponser_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponser_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_link', models.URLField()),
                ('product_images', models.ImageField(upload_to='pricecomparision/static/images')),
            ],
        ),
    ]
