# Generated by Django 4.1.4 on 2023-03-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sponser_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sponser_products',
            new_name='sp_product',
        ),
    ]
