# Generated by Django 4.1.4 on 2023-03-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_sponser_products_sp_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp_product',
            old_name='product_images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sp_product',
            old_name='product_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='sp_product',
            old_name='product_name',
            new_name='name',
        ),
    ]
