# Generated by Django 4.1.4 on 2023-03-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_product_images_sp_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_product',
            name='image',
            field=models.ImageField(upload_to='dbimg'),
        ),
    ]
